apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapp-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: webapp
          image: webapp:v1
          ports:
            - containerPort: 8080
          env:
            - name: APP_COLOR
              value: "pink"
            - name: DBHOST
              value: "mysql-service-svc-mysql-ns.local"
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              value: "root"
            - name: DBPWD
              value: "my-secret-pw"
            - name: DATABASE
              value: "mydb"
