piVersion: v1
kind: Pod
metadata:
  name: webapp-pod-blue
  namespace: webapp-ns
  labels:
    app: employees
    color: blue
spec:
  containers:
    - name: webapp
      image: webapp:v1
      ports:
        - containerPort: 8080
      env:
        - name: APP_COLOR
          value: "blue"
        - name: DBHOST
          value: "mysql-service"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "my-secret-pw"
        - name: DATABASE
          value: "mydb"
