apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-rs
  namespace: webapp-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: webapp
          image: ${ECR_REGISTRY}/webapp-repo:v1.0
          ports:
            - containerPort: 8080
          env:
            - name: APP_COLOR
              value: "blue"
            - name: DBHOST
              value: "mysql-service"
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              value: "root"
            - name: DBPWD
              value: "my-secret-pw"
            - name: DATABASE
              value: "mydb"
